### ISSUE TITLE
Crash due to null node locator when using the nested probe UI with circular attributes

### ISSUE THREAD

**Issue by creichen** [creichen/codeprober#4]
`EvaluatePropertyHandler` can try to build a `Tracing` object with a null node locator.

Reported during EDAP15, homework 2024-ex3.
This may or may not be an upstream issue.

# Steps to reproduce

`./codeprober/code-prober-dev.jar ./code-prober.sh examples/hw3-task-1-0.teal`
- Probe for `IfStmt.controlFalse`
- Open nested probe table
- try to load `getCond()`

![image](https://github.com/creichen/codeprober/assets/5527947/9944c02c-a1d0-4aa6-9c95-29f17a4b4db2)

# Workarounds

Does not seem to trigger with non-recursive probes.  Opening a separate probe window for the `ControlFalse` node works fine:

![image](https://github.com/creichen/codeprober/assets/5527947/05bd1253-5188-4e7a-a0f6-a61a065ff3b1)

# Cause analysis

Incomplete:

```
Exception in thread "Thread-27" java.lang.NullPointerException
	at codeprober.protocol.data.Tracing.toJSON(Tracing.java:27)
	at codeprober.protocol.data.RpcBodyLine.toJSON(RpcBodyLine.java:156)
	at codeprober.protocol.data.SynchronousEvaluationResult.lambda$toJSON$4(SynchronousEvaluationResult.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at codeprober.protocol.data.SynchronousEvaluationResult.toJSON(SynchronousEvaluationResult.java:63)
	at codeprober.protocol.data.PropertyEvaluationResult.toJSON(PropertyEvaluationResult.java:57)
	at codeprober.protocol.data.EvaluatePropertyRes.toJSON(EvaluatePropertyRes.java:18)
	at codeprober.protocol.data.RequestAdapter.handle(RequestAdapter.java:21)
	at codeprober.DefaultRequestHandler.handleRequest(DefaultRequestHandler.java:273)
	at codeprober.requesthandler.RequestHandlerMonitor.process(RequestHandlerMonitor.java:64)
	at codeprober.requesthandler.RequestHandlerMonitor.lambda$submit$0(RequestHandlerMonitor.java:27)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The immediate underlying cause is an invocation of `TracingBuilder.Tracing.finish(null)` (where `null` is not intended as a valid argument):

```
	at codeprober.requesthandler.TracingBuilder.finish(TracingBuilder.java:102)
	at codeprober.requesthandler.EvaluatePropertyHandler.lambda$apply$3(EvaluatePropertyHandler.java:319)
	at codeprober.requesthandler.EvaluatePropertyHandler.lambda$apply$6(EvaluatePropertyHandler.java:357)
	at codeprober.metaprogramming.StdIoInterceptor.performLiveCaptured(StdIoInterceptor.java:73)
	at codeprober.requesthandler.EvaluatePropertyHandler.lambda$apply$7(EvaluatePropertyHandler.java:354)
	at codeprober.metaprogramming.StdIoInterceptor.performLiveCaptured(StdIoInterceptor.java:73)
	at codeprober.metaprogramming.StdIoInterceptor.performCaptured(StdIoInterceptor.java:82)
	at codeprober.requesthandler.EvaluatePropertyHandler.apply(EvaluatePropertyHandler.java:348)
	at codeprober.DefaultRequestHandler$1.handleEvaluateProperty(DefaultRequestHandler.java:260)
	at codeprober.protocol.data.RequestAdapter.handle(RequestAdapter.java:21)
	at codeprober.DefaultRequestHandler.handleRequest(DefaultRequestHandler.java:273)
	at codeprober.requesthandler.RequestHandlerMonitor.process(RequestHandlerMonitor.java:64)
	at codeprober.requesthandler.RequestHandlerMonitor.lambda$submit$0(RequestHandlerMonitor.java:27)
	at java.base/java.lang.Thread.run(Thread.java:829)
	```
	
Line number might be off a little due to two lines of instrumentation in `TracingBuilder.java`.

**Comment by Kevlanche** [comment]
This is fixed upstream by https://github.com/lu-cs-sde/codeprober/commit/2d84937f72a897f211775db12bd0fba1984b8bdd

**Comment by creichen** [comment]
Merged into the `teal` branch.  Thank you, @Kevlanche !
